export const weaponComponents: any = {
  WEAPON_PISTOL: [
    'COMPONENT_AT_PI_FLSH',
    'COMPONENT_PISTOL_CLIP_02',
    'COMPONENT_AT_PI_SUPP_02',
    'COMPONENT_PISTOL_VARMOD_LUXE',
  ],
  WEAPON_CARBINERIFLE: [
    'COMPONENT_CARBINERIFLE_CLIP_03',
    '	COMPONENT_AT_AR_FLSH',
    'COMPONENT_AT_SCOPE_MEDIUM',
    'COMPONENT_AT_AR_SUPP',
    'COMPONENT_AT_AR_AFGRIP',
    'COMPONENT_CARBINERIFLE_VARMOD_LUXE',
  ],
};
